version: '3'

tasks:
  fmt:
    cmds:
      - go fmt ./...
  lint:
    cmds:
      - golangci-lint run
  protoc:
    cmds:
      - protoc -I protos/proto protos/proto/* --go_out=./protos/gen --go_opt=paths=source_relative --go-grpc_out=./protos/gen --go-grpc_opt=paths=source_relative
  create-migration:
    cmds:
      - migrate create -ext sql -dir database/migrations {{.CLI_ARGS}}
  migrate:
    cmds:
      - migrate -source file://database/migrations -database "postgres://user:password@localhost:5432/exception-control?sslmode=disable" up
  migrate-down:
    cmds:
      - migrate -source file://database/migrations -database "postgres://user:password@localhost:5432/exception-control?sslmode=disable" down
  sqlc-generate:
    cmds:
      - sqlc generate
