version: "3.5"

networks:
  exception-control-network:
    driver: bridge

volumes:
  pgsql:
    driver: local

services:
  app:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    ports:
      - "80:80"
    networks:
      - exception-control-network

  psql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - exception-control-network